### ISSUE TITLE
Requested feature: Add import support from other formats

### ISSUE THREAD

**Issue by alexbfree** [hestiaAI/json-ld-semantics#24]
It would be nice to be able to construct the tree/model from other common data formats we see in company-returned data so that the tool can be used on all data.

Most importantly, CSV. These are very common.

Others we have also seen:
- Various forms of XML (.XML, .KML, .TCX, strict HTML) (these should map easily onto a tree format)
- Tab separated value (usually saved as .TXT sometimes .TSV)
- Formatted table within PDF (not sure how easy this is to extract)

**Comment by Amustache** [comment]
- [ ] #34 : It is one of the objective.
- [ ] #35 : This should be pretty straighforward.
- [ ] #36 : This _should_ works well, I believe.
- [ ] #37 : This will be a challenge for sure...
